// This file is auto-generated by @hey-api/openapi-ts

/**
 * APIKeyResponse
 */
export type ApiKeyResponse = {
    /**
     * Has Api Key
     */
    has_api_key: boolean;
    /**
     * Masked Key
     */
    masked_key?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * APIKeySet
 */
export type ApiKeySet = {
    /**
     * Api Key
     * Plaintext API key to encrypt and store
     */
    api_key: string;
};

/**
 * Body_upload_document
 */
export type BodyUploadDocument = {
    /**
     * File
     * PDF file to upload (max 50MB)
     */
    file: string;
    /**
     * Language
     * Document language code: en, fr, ar
     */
    language?: string;
};

/**
 * CollectionCreate
 */
export type CollectionCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * CollectionDocumentResponse
 */
export type CollectionDocumentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Language
     */
    language: string;
    /**
     * Status
     */
    status: string;
};

/**
 * CollectionDocumentsResponse
 */
export type CollectionDocumentsResponse = {
    /**
     * Documents
     */
    documents: Array<CollectionDocumentResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * CollectionListResponse
 */
export type CollectionListResponse = {
    /**
     * Collections
     */
    collections: Array<CollectionResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * CollectionResponse
 */
export type CollectionResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * DocumentListResponse
 * Response for list of documents.
 */
export type DocumentListResponse = {
    /**
     * Documents
     */
    documents: Array<DocumentResponse>;
    /**
     * Total
     */
    total: number;
};

/**
 * DocumentResponse
 * Document response schema returned by the API.
 */
export type DocumentResponse = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Language
     */
    language: string;
    /**
     * Status
     */
    status: string;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Page Count
     */
    page_count?: number | null;
    /**
     * Detected Languages
     */
    detected_languages?: Array<string> | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IngestionStatusListResponse
 * Paginated list of document ingestion statuses.
 */
export type IngestionStatusListResponse = {
    /**
     * Documents
     */
    documents: Array<IngestionStatusResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Skip
     */
    skip: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * IngestionStatusResponse
 * Enriched document status response for ingestion dashboard.
 */
export type IngestionStatusResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Submitted Language
     */
    submitted_language: string;
    /**
     * Status
     */
    status: string;
    /**
     * Page Count
     */
    page_count?: number | null;
    /**
     * Chunk Count
     */
    chunk_count?: number;
    /**
     * Failed Blocks
     */
    failed_blocks?: number;
    /**
     * Error Log
     */
    error_log?: {
        [key: string]: unknown;
    } | null;
    /**
     * Detected Languages
     */
    detected_languages?: Array<string> | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * LLMProviderCreate
 */
export type LlmProviderCreate = {
    /**
     * Provider Type
     * openai | anthropic | ollama
     */
    provider_type: 'openai' | 'anthropic' | 'ollama';
    /**
     * Base Url
     * None for Ollama default
     */
    base_url?: string | null;
    /**
     * Api Version
     * e.g. 'v1' for OpenAI
     */
    api_version?: string | null;
};

/**
 * LLMProviderListResponse
 */
export type LlmProviderListResponse = {
    /**
     * Items
     */
    items: Array<LlmProviderResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Skip
     */
    skip: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * LLMProviderResponse
 */
export type LlmProviderResponse = {
    /**
     * Provider Type
     * openai | anthropic | ollama
     */
    provider_type: 'openai' | 'anthropic' | 'ollama';
    /**
     * Base Url
     * None for Ollama default
     */
    base_url?: string | null;
    /**
     * Api Version
     * e.g. 'v1' for OpenAI
     */
    api_version?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Has Api Key
     */
    has_api_key?: boolean;
    /**
     * Warning
     */
    warning?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * LLMProviderUpdate
 */
export type LlmProviderUpdate = {
    /**
     * Base Url
     */
    base_url?: string | unknown | null;
    /**
     * Api Version
     */
    api_version?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * ModelAssignmentCreate
 */
export type ModelAssignmentCreate = {
    /**
     * Provider Id
     * FK to llm_providers.id
     */
    provider_id: string;
    /**
     * Model Name
     * e.g. gpt-4o, claude-3-5-sonnet
     */
    model_name: string;
    /**
     * System Function
     * retrieval | generation | evaluation
     */
    system_function: 'retrieval' | 'generation' | 'evaluation';
};

/**
 * ModelAssignmentListResponse
 */
export type ModelAssignmentListResponse = {
    /**
     * Items
     */
    items: Array<ModelAssignmentResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Skip
     */
    skip: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * ModelAssignmentResponse
 */
export type ModelAssignmentResponse = {
    /**
     * Provider Id
     * FK to llm_providers.id
     */
    provider_id: string;
    /**
     * Model Name
     * e.g. gpt-4o, claude-3-5-sonnet
     */
    model_name: string;
    /**
     * System Function
     * retrieval | generation | evaluation
     */
    system_function: 'retrieval' | 'generation' | 'evaluation';
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Health Status
     */
    health_status?: string | null;
    /**
     * Health Message
     */
    health_message?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ModelAssignmentUpdate
 */
export type ModelAssignmentUpdate = {
    /**
     * Model Name
     */
    model_name?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Provider Id
     */
    provider_id?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/documents/';
};

export type ListDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentsError = ListDocumentsErrors[keyof ListDocumentsErrors];

export type ListDocumentsResponses = {
    /**
     * Successful Response
     */
    200: DocumentListResponse;
};

export type ListDocumentsResponse = ListDocumentsResponses[keyof ListDocumentsResponses];

export type UploadDocumentData = {
    body: BodyUploadDocument;
    path?: never;
    query?: never;
    url: '/api/v1/documents/';
};

export type UploadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDocumentError = UploadDocumentErrors[keyof UploadDocumentErrors];

export type UploadDocumentResponses = {
    /**
     * Successful Response
     */
    201: DocumentResponse;
};

export type UploadDocumentResponse = UploadDocumentResponses[keyof UploadDocumentResponses];

export type ProcessDocumentEndpointData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/process';
};

export type ProcessDocumentEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessDocumentEndpointError = ProcessDocumentEndpointErrors[keyof ProcessDocumentEndpointErrors];

export type ProcessDocumentEndpointResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetIngestionStatusData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: 'pending' | 'processing' | 'processed' | 'failed' | null;
    };
    url: '/api/v1/documents/ingestion-status';
};

export type GetIngestionStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIngestionStatusError = GetIngestionStatusErrors[keyof GetIngestionStatusErrors];

export type GetIngestionStatusResponses = {
    /**
     * Successful Response
     */
    200: IngestionStatusListResponse;
};

export type GetIngestionStatusResponse = GetIngestionStatusResponses[keyof GetIngestionStatusResponses];

export type GetDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/';
};

export type GetDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentError = GetDocumentErrors[keyof GetDocumentErrors];

export type GetDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentResponse;
};

export type GetDocumentResponse = GetDocumentResponses[keyof GetDocumentResponses];

export type ListCollectionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         * Number of records to skip
         */
        skip?: number;
        /**
         * Limit
         * Max records to return
         */
        limit?: number;
    };
    url: '/api/v1/collections/';
};

export type ListCollectionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCollectionsError = ListCollectionsErrors[keyof ListCollectionsErrors];

export type ListCollectionsResponses = {
    /**
     * Successful Response
     */
    200: CollectionListResponse;
};

export type ListCollectionsResponse = ListCollectionsResponses[keyof ListCollectionsResponses];

export type CreateCollectionData = {
    body: CollectionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/collections/';
};

export type CreateCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCollectionError = CreateCollectionErrors[keyof CreateCollectionErrors];

export type CreateCollectionResponses = {
    /**
     * Successful Response
     */
    201: CollectionResponse;
};

export type CreateCollectionResponse = CreateCollectionResponses[keyof CreateCollectionResponses];

export type DeleteCollectionData = {
    body?: never;
    path: {
        /**
         * Collection Id
         */
        collection_id: string;
    };
    query?: never;
    url: '/api/v1/collections/{collection_id}/';
};

export type DeleteCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCollectionError = DeleteCollectionErrors[keyof DeleteCollectionErrors];

export type DeleteCollectionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCollectionResponse = DeleteCollectionResponses[keyof DeleteCollectionResponses];

export type GetCollectionData = {
    body?: never;
    path: {
        /**
         * Collection Id
         */
        collection_id: string;
    };
    query?: never;
    url: '/api/v1/collections/{collection_id}/';
};

export type GetCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCollectionError = GetCollectionErrors[keyof GetCollectionErrors];

export type GetCollectionResponses = {
    /**
     * Successful Response
     */
    200: CollectionResponse;
};

export type GetCollectionResponse = GetCollectionResponses[keyof GetCollectionResponses];

export type ListDocumentsInCollectionData = {
    body?: never;
    path: {
        /**
         * Collection Id
         */
        collection_id: string;
    };
    query?: never;
    url: '/api/v1/collections/{collection_id}/documents/';
};

export type ListDocumentsInCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentsInCollectionError = ListDocumentsInCollectionErrors[keyof ListDocumentsInCollectionErrors];

export type ListDocumentsInCollectionResponses = {
    /**
     * Successful Response
     */
    200: CollectionDocumentsResponse;
};

export type ListDocumentsInCollectionResponse = ListDocumentsInCollectionResponses[keyof ListDocumentsInCollectionResponses];

export type AddDocumentsToCollectionData = {
    /**
     * Document Ids
     */
    body: Array<string>;
    path: {
        /**
         * Collection Id
         */
        collection_id: string;
    };
    query?: never;
    url: '/api/v1/collections/{collection_id}/documents/';
};

export type AddDocumentsToCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddDocumentsToCollectionError = AddDocumentsToCollectionErrors[keyof AddDocumentsToCollectionErrors];

export type AddDocumentsToCollectionResponses = {
    /**
     * Successful Response
     */
    201: CollectionDocumentsResponse;
};

export type AddDocumentsToCollectionResponse = AddDocumentsToCollectionResponses[keyof AddDocumentsToCollectionResponses];

export type RemoveDocumentFromCollectionData = {
    body?: never;
    path: {
        /**
         * Collection Id
         */
        collection_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/collections/{collection_id}/documents/{document_id}/';
};

export type RemoveDocumentFromCollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveDocumentFromCollectionError = RemoveDocumentFromCollectionErrors[keyof RemoveDocumentFromCollectionErrors];

export type RemoveDocumentFromCollectionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveDocumentFromCollectionResponse = RemoveDocumentFromCollectionResponses[keyof RemoveDocumentFromCollectionResponses];

export type ListLlmProvidersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/llm-providers/';
};

export type ListLlmProvidersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLlmProvidersError = ListLlmProvidersErrors[keyof ListLlmProvidersErrors];

export type ListLlmProvidersResponses = {
    /**
     * Successful Response
     */
    200: LlmProviderListResponse;
};

export type ListLlmProvidersResponse = ListLlmProvidersResponses[keyof ListLlmProvidersResponses];

export type CreateLlmProviderData = {
    body: LlmProviderCreate;
    path?: never;
    query?: never;
    url: '/api/v1/llm-providers/';
};

export type CreateLlmProviderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLlmProviderError = CreateLlmProviderErrors[keyof CreateLlmProviderErrors];

export type CreateLlmProviderResponses = {
    /**
     * Successful Response
     */
    201: LlmProviderResponse;
};

export type CreateLlmProviderResponse = CreateLlmProviderResponses[keyof CreateLlmProviderResponses];

export type DeleteLlmProviderData = {
    body?: never;
    path: {
        /**
         * Provider Id
         */
        provider_id: string;
    };
    query?: never;
    url: '/api/v1/llm-providers/{provider_id}';
};

export type DeleteLlmProviderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLlmProviderError = DeleteLlmProviderErrors[keyof DeleteLlmProviderErrors];

export type DeleteLlmProviderResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteLlmProviderResponse = DeleteLlmProviderResponses[keyof DeleteLlmProviderResponses];

export type GetLlmProviderData = {
    body?: never;
    path: {
        /**
         * Provider Id
         */
        provider_id: string;
    };
    query?: never;
    url: '/api/v1/llm-providers/{provider_id}';
};

export type GetLlmProviderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLlmProviderError = GetLlmProviderErrors[keyof GetLlmProviderErrors];

export type GetLlmProviderResponses = {
    /**
     * Successful Response
     */
    200: LlmProviderResponse;
};

export type GetLlmProviderResponse = GetLlmProviderResponses[keyof GetLlmProviderResponses];

export type UpdateLlmProviderData = {
    body: LlmProviderUpdate;
    path: {
        /**
         * Provider Id
         */
        provider_id: string;
    };
    query?: never;
    url: '/api/v1/llm-providers/{provider_id}';
};

export type UpdateLlmProviderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLlmProviderError = UpdateLlmProviderErrors[keyof UpdateLlmProviderErrors];

export type UpdateLlmProviderResponses = {
    /**
     * Successful Response
     */
    200: LlmProviderResponse;
};

export type UpdateLlmProviderResponse = UpdateLlmProviderResponses[keyof UpdateLlmProviderResponses];

export type DeleteProviderApiKeyData = {
    body?: never;
    path: {
        /**
         * Provider Id
         */
        provider_id: string;
    };
    query?: never;
    url: '/api/v1/llm-providers/{provider_id}/api-key';
};

export type DeleteProviderApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProviderApiKeyError = DeleteProviderApiKeyErrors[keyof DeleteProviderApiKeyErrors];

export type DeleteProviderApiKeyResponses = {
    /**
     * Successful Response
     */
    200: ApiKeyResponse;
};

export type DeleteProviderApiKeyResponse = DeleteProviderApiKeyResponses[keyof DeleteProviderApiKeyResponses];

export type GetProviderApiKeyStatusData = {
    body?: never;
    path: {
        /**
         * Provider Id
         */
        provider_id: string;
    };
    query?: never;
    url: '/api/v1/llm-providers/{provider_id}/api-key';
};

export type GetProviderApiKeyStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProviderApiKeyStatusError = GetProviderApiKeyStatusErrors[keyof GetProviderApiKeyStatusErrors];

export type GetProviderApiKeyStatusResponses = {
    /**
     * Successful Response
     */
    200: ApiKeyResponse;
};

export type GetProviderApiKeyStatusResponse = GetProviderApiKeyStatusResponses[keyof GetProviderApiKeyStatusResponses];

export type SetProviderApiKeyData = {
    body: ApiKeySet;
    path: {
        /**
         * Provider Id
         */
        provider_id: string;
    };
    query?: never;
    url: '/api/v1/llm-providers/{provider_id}/api-key';
};

export type SetProviderApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetProviderApiKeyError = SetProviderApiKeyErrors[keyof SetProviderApiKeyErrors];

export type SetProviderApiKeyResponses = {
    /**
     * Successful Response
     */
    201: ApiKeyResponse;
};

export type SetProviderApiKeyResponse = SetProviderApiKeyResponses[keyof SetProviderApiKeyResponses];

export type ListModelAssignmentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * System Function
         * Filter by system function
         */
        system_function?: string | null;
    };
    url: '/api/v1/model-assignments/';
};

export type ListModelAssignmentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListModelAssignmentsError = ListModelAssignmentsErrors[keyof ListModelAssignmentsErrors];

export type ListModelAssignmentsResponses = {
    /**
     * Successful Response
     */
    200: ModelAssignmentListResponse;
};

export type ListModelAssignmentsResponse = ListModelAssignmentsResponses[keyof ListModelAssignmentsResponses];

export type CreateModelAssignmentData = {
    body: ModelAssignmentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/model-assignments/';
};

export type CreateModelAssignmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateModelAssignmentError = CreateModelAssignmentErrors[keyof CreateModelAssignmentErrors];

export type CreateModelAssignmentResponses = {
    /**
     * Successful Response
     */
    201: ModelAssignmentResponse;
};

export type CreateModelAssignmentResponse = CreateModelAssignmentResponses[keyof CreateModelAssignmentResponses];

export type DeleteModelAssignmentData = {
    body?: never;
    path: {
        /**
         * Assignment Id
         */
        assignment_id: string;
    };
    query?: never;
    url: '/api/v1/model-assignments/{assignment_id}';
};

export type DeleteModelAssignmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteModelAssignmentError = DeleteModelAssignmentErrors[keyof DeleteModelAssignmentErrors];

export type DeleteModelAssignmentResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteModelAssignmentResponse = DeleteModelAssignmentResponses[keyof DeleteModelAssignmentResponses];

export type GetModelAssignmentData = {
    body?: never;
    path: {
        /**
         * Assignment Id
         */
        assignment_id: string;
    };
    query?: never;
    url: '/api/v1/model-assignments/{assignment_id}';
};

export type GetModelAssignmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetModelAssignmentError = GetModelAssignmentErrors[keyof GetModelAssignmentErrors];

export type GetModelAssignmentResponses = {
    /**
     * Successful Response
     */
    200: ModelAssignmentResponse;
};

export type GetModelAssignmentResponse = GetModelAssignmentResponses[keyof GetModelAssignmentResponses];

export type UpdateModelAssignmentData = {
    body: ModelAssignmentUpdate;
    path: {
        /**
         * Assignment Id
         */
        assignment_id: string;
    };
    query?: never;
    url: '/api/v1/model-assignments/{assignment_id}';
};

export type UpdateModelAssignmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateModelAssignmentError = UpdateModelAssignmentErrors[keyof UpdateModelAssignmentErrors];

export type UpdateModelAssignmentResponses = {
    /**
     * Successful Response
     */
    200: ModelAssignmentResponse;
};

export type UpdateModelAssignmentResponse = UpdateModelAssignmentResponses[keyof UpdateModelAssignmentResponses];

export type PingModelAssignmentData = {
    path: {
        assignment_id: string;
    };
    query?: never;
    url: '/api/v1/model-assignments/{assignment_id}/ping';
};

export type PingModelAssignmentErrors = {
    422: HttpValidationError;
};

export type PingModelAssignmentError = PingModelAssignmentErrors[keyof PingModelAssignmentErrors];

export type PingModelAssignmentResponses = {
    200: ModelAssignmentResponse;
};

export type PingModelAssignmentResponse = PingModelAssignmentResponses[keyof PingModelAssignmentResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};
